### ISSUE TITLE
Stress importance of starting msys for specific system

### ISSUE THREAD

**Issue by gvissers** [pjbroad/el-build-methods#3]
from the building elc with msys2 readme:

>Using a Msys2 terminal for your specific system

Might be worth stressing a bit more that you need to start msys2 specifically for the build environment you want, not simply the generic msys2 environment. I had a bit of trouble figuring out why MINGW_PACKAGE_PREFIX was not set.

**Comment by pjbroad** [comment]
Thanks for the comment.  I've updated the text though the the scripts included do not run in the standard terminal and do print a console message to say why.
